[parity]
chain = "ethereum"
mode = "active"
no_download = false

[rpc]
disable = false
port = 8545
interface = "local"
cors = []
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["none"]

#[network]
#min_peers = 25
#max_peers = 50
