[footprint]
pruning = "fast"

[parity]
chain = "ethereum"
mode = "active"
no_download = false

[rpc]
disable = false
port = 8545
interface = "all"
cors = []
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub", "personal"]
hosts = ["none"]

[network]
min_peers = 300
max_peers = 300
